version: "3.7"
networks:
  net-dev:
    driver: bridge
services:
  postgres:
    container_name: postgres
    image: arm64v8/postgres
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=root
      - POSTGRES_DB=example_db
    volumes:
      - postgres_db:/var/lib/postgresql/data
    ports:
      - "3306:5432"
    networks:
      - net-dev
volumes:
  postgres_db:
    driver: local